PresentationLayer2/Models/MyreservationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationLayer2.Models
{
    public class MyreservationViewModel
    {
        [Key]
        public int BookingID { get; set; }
        public int UserID { get; set; }
        public int TimeslotID { get; set; }
        public string Day { get; set; }
        public string Timeslot { get; set; }
        public int Currentreservation { get; set; }
        public int Maxreservations { get; set; }
        public string Programname { get; set; }

        public int ProgramId { get; set; }

        public MyreservationViewModel()
        {

        }

        public MyreservationViewModel(string programname)
        {
            this.Programname = programname;
        }

        public MyreservationViewModel(int bookingid, int userid, int timeslotid, string day, string timeslot, int currentres, int maxres, string programname)
        {
            this.BookingID = bookingid;
            this.UserID = userid;
            this.TimeslotID = timeslotid;
            this.Day = day;
            this.Timeslot = timeslot;
            this.Currentreservation = currentres;
            this.Maxreservations = maxres;
            this.Programname = programname;
        }
    }
}

PresentationLayer2/Controllers/MyreservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using DatabaseLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresentationLayer2.Data;
using PresentationLayer2.Models;

namespace PresentationLayer2.Controllers
{
    public class MyreservationController : Controller
    {
        ReservationContainer reservationContainer = new ReservationContainer(new ReservationDAL());
        Reservation reservation1 = new Reservation(new ReservationDAL());
        ProgramContainer programContainer = new ProgramContainer(new ProgramDAL());
        MachineContainer machineContainer = new MachineContainer(new MachineDAL());
        ProgramMachineContainer programmachineContainer = new ProgramMachineContainer(new ProgramMachineDAL());



        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            MyreservationViewModel myreservationViewmodel = new MyreservationViewModel();
            ListViewModel list = new ListViewModel();

            int userId = Convert.ToInt32(HttpContext.Session.GetInt32("UserID"));

            //list van reserveringen vullen
            foreach (Reservation reservation in reservationContainer.GetAllReservationsById(userId))
            {
                reservation.Currentreservations = reservation1.CurrentReservations(reservation.TimeslotID);
                myreservationViewmodel = new MyreservationViewModel(reservation.BookingID, reservation.UserID, reservation.TimeslotID, reservation.Timeslot.Day, reservation.Timeslot.Timeslot, reservation.Currentreservations, reservation.Timeslot.Maxreservations, reservation.Program.Programname);
                list.myreservations.Add(myreservationViewmodel);
            }

            return View(list.myreservations);
        }


        [HttpGet]
        public IActionResult ChangeProgram(int id, string searchPhrase)
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            MachineViewModel machineViewModel = new MachineViewModel();
            ProgramViewModel programViewModel = new ProgramViewModel();
            MachineAndMyreservationViewModel joined = new MachineAndMyreservationViewModel();           

            joined.myreservation = FetchById(id);

            //viewbag aanmaken
            var programs = new List<string>();
            foreach(BusinessLogicLayer.Program program in programContainer.GetAllPrograms())
            {
                programs.Add(program.ProgramName);
            }
            ViewBag.allprograms = programs;

            //zoekfunctie
            if (!String.IsNullOrEmpty(searchPhrase))
            {
                BusinessLogicLayer.Program program = programContainer.GetOneProgramByName(searchPhrase);

                foreach (ProgramMachine machine in programmachineContainer.GetAllProgramMachinesById(program.ProgramId))
                {
                    machineViewModel = new MachineViewModel(machine.MachineID, machine.Machine.Machinetype, machine.Machine.Machinename, machine.Machine.Machinedescription);
                    joined.machines.Add(machineViewModel);
                }
            }
                return View(joined);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ChangeProgram(int id, MachineAndMyreservationViewModel joinedViewModel)
        {
            BusinessLogicLayer.Program program = programContainer.GetOneProgramByName(joinedViewModel.myreservation.Programname);
            Reservation reser = new Reservation(id, program.ProgramId);

            reservation1.EditOneReservationById(reser);

            TempData["ProgramChanged"] = "Program has been changed to '"+ joinedViewModel.myreservation.Programname+"'";

            return RedirectToAction(nameof(Index));
        }


        public IActionResult Cancel(int id)
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            MyreservationViewModel myreservationViewModel = new MyreservationViewModel();
            myreservationViewModel = FetchById(id);
            return View(myreservationViewModel);
        }


        [HttpPost, ActionName("Cancel")]
        [ValidateAntiForgeryToken]
        public IActionResult CancelConfirmed(int id, MyreservationViewModel myreservationViewModel)
        {
            reservationContainer.DeleteOneReservationByBookingId(id);

            TempData["ReservationCancelled"] = "Reservation at '"+myreservationViewModel.Day+ "''" + myreservationViewModel.Timeslot+ "' has been cancelled";

            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public MyreservationViewModel FetchById(int id)
        {
            MyreservationViewModel myreservationViewModel = new MyreservationViewModel();

            Reservation reservation = reservationContainer.GetOneReservationsById(id);
            {
                myreservationViewModel.BookingID = reservation.BookingID;
                myreservationViewModel.TimeslotID = reservation.TimeslotID;
                myreservationViewModel.UserID = reservation.UserID;
                myreservationViewModel.ProgramId = reservation.ProgramID;
                myreservationViewModel.Day = reservation.Timeslot.Day;
                myreservationViewModel.Timeslot = reservation.Timeslot.Timeslot;
                reservation.Currentreservations = reservation1.CurrentReservations(reservation.TimeslotID);
                myreservationViewModel.Currentreservation = reservation.Currentreservations;
                myreservationViewModel.Maxreservations = reservation.Timeslot.Maxreservations;
                myreservationViewModel.Programname = reservation.Program.Programname;
            }

            return myreservationViewModel;
        }
    }
}

PresentationLayer2/Views/Myreservation/Cancel.cshtml
@model PresentationLayer2.Models.MyreservationViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Cancel reservation</h1>

<h3>Are you sure you want to cancel this reservation?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timeslot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timeslot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currentreservation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currentreservation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maxreservations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maxreservations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programname)
        </dd>
    </dl>
    
    <form asp-action="Cancel">
        <input type="hidden" asp-for="BookingID" />
        <input type="hidden" asp-for="Day" />
        <input type="hidden" asp-for="Timeslot" />
        <input type="submit" value="CancelReservation" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PresentationLayer2/Views/Myreservation/ChangeProgram.cshtml
@model PresentationLayer2.Models.MachineAndMyreservationViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Change Program</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ChangeProgram">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.myreservation.Day)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.myreservation.Day)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.myreservation.Timeslot)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.myreservation.Timeslot)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.myreservation.Currentreservation)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.myreservation.Currentreservation)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.myreservation.Maxreservations)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.myreservation.Maxreservations)
            </dd>
            <div class="form-group">
                @Html.DropDownListFor(Model => Model.myreservation.Programname, new SelectList(ViewBag.allprograms))
                <label asp-for="myreservation.Programname" class="control-label"></label>
                @*<input asp-for="Usertype" class="form-control" />*@
                <span asp-validation-for="myreservation.Programname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<p></p>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<p></p>

<form method="get" autocomplete="off">
    @using (Html.BeginForm("ChangeProgram", "Myreservation", FormMethod.Get))
    {
        <p>Select MachineType</p>
        @Html.DropDownList("searchPhrase", new SelectList((System.Collections.IEnumerable)ViewData["allprograms"]))
        <input type="hidden" asp-for="myreservation.ProgramId" />
        <input type="submit" value="search" />
        <p></p>
    }
</form>

<p></p>

<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>
                MachineType
            </th>
            <th>
                MachineName
            </th>
            <th>
                MachineDescription
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.machines)
        {
            <tr>
                <td>
                    @Html.DisplayFor(Modelitem => item.Machinetype)
                </td>
                <td>
                    @Html.DisplayFor(Modelitem => item.Machinename)
                </td>
                <td>
                    @Html.DisplayFor(Modelitem => item.Machinedescription)
                </td>
            </tr>
        }
    </tbody>
</table>

PresentationLayer2/Views/Myreservation/Details.cshtml
@model PresentationLayer2.Models.MyreservationViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Account/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>MyreservationViewModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeslotID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeslotID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timeslot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timeslot)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Currentreservation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Currentreservation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Maxreservations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Maxreservations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Programname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Programname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProgramId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProgramId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BookingID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PresentationLayer2/Views/Myreservation/Index.cshtml
@model IEnumerable<PresentationLayer2.Models.MyreservationViewModel>

@{
    ViewData["Title"] = "MyReservations";
}

<div class="jumbotron-fluid">
    <h1 class="text-center">@ViewData["Title"]</h1>
</div>

@if (TempData["ProgramChanged"] != null)
{
    <div class="alert alert-success">
        <strong> Succes! </strong>  @TempData["ProgramChanged"]
    </div>
}
@if (TempData["ReservationCancelled"] != null)
{
    <div class="alert alert-success">
        <strong> Succes! </strong>  @TempData["ReservationCancelled"]
    </div>
}
<p>

</p>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            @*<th>
                    @Html.DisplayNameFor(model => model.UserID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TimeslotID)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Day)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timeslot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Currentreservation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Maxreservations)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Programname)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.ProgramId)
                </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                @*<td>
                        @Html.DisplayFor(modelItem => item.UserID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeslotID)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Day)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timeslot)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Currentreservation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Maxreservations)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Programname)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.ProgramId)
                    </td>*@
                <td>
                    <a asp-action="ChangeProgram" asp-route-id="@item.BookingID">ChangeProgram</a> |
                    <a asp-action="Cancel" asp-route-id="@item.BookingID">Cancel</a>
                </td>
            </tr>
        }
    </tbody>
</table>