PresentationLayer2/Models/TimeslotViewModel.cs
using BusinessLogicLayer;
using DatabaseLayer;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace PresentationLayer2.Models
{
    public class TimeslotViewModel
    {
        [Key]
        public int TimeslotID { get; set; }
        [Required]
        public string Day { get; set; }
        [Required]
        public string Timeslots { get; set; }
        [Required]
        public int Currentreservations { get; set; }
        [Required]
        public int Maxreservations { get; set; }

        public TimeslotViewModel()
        {

        }

        public TimeslotViewModel(int id, string day, string timeslots, int currentres, int maxres)
        {
            this.TimeslotID = id;
            this.Day = day;
            this.Timeslots = timeslots;
            this.Currentreservations = currentres;
            this.Maxreservations = maxres;
        }
    }
}

PresentationLayer2/Controllers/TimeslotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using DatabaseLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PresentationLayer2.Data;
using PresentationLayer2.Models;

namespace PresentationLayer2.Controllers
{
    public class TimeslotController : Controller
    {
        Timeslot timeslot = new Timeslot(new TimeslotDAL());
        TimeslotContainer timeslotContainer = new TimeslotContainer(new TimeslotDAL());
        Reservation reservation = new Reservation(new ReservationDAL());
        ReservationContainer reservationContainer = new ReservationContainer(new ReservationDAL());


        public IActionResult Index(string searchPhrase)
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            TimeslotViewModel timeslotViewmodel = new TimeslotViewModel();
            ListViewModel list = new ListViewModel();

            //list vullen met alle tijdsloten
            foreach (Timeslot timeslot in timeslotContainer.GetAllTimeslots())
            {
                timeslotViewmodel = new TimeslotViewModel(timeslot.TimeslotID, timeslot.Day, timeslot.Timeslots, timeslot.Currentreservations, timeslot.Maxreservations);
                list.alltimeslots.Add(timeslotViewmodel);
            }

            //zoekfunctie
            if (!String.IsNullOrEmpty(searchPhrase))
            {
                list.alltimeslots.Clear();
                foreach (Timeslot timeslot in timeslotContainer.GetTimeslotsByDay(searchPhrase))
                {
                    timeslotViewmodel = new TimeslotViewModel(timeslot.TimeslotID, timeslot.Day, timeslot.Timeslots, timeslot.Currentreservations, timeslot.Maxreservations);
                    list.alltimeslots.Add(timeslotViewmodel);
                }
                if (list.alltimeslots.Count < 1)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(list.alltimeslots);
        }


        public IActionResult Create()
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            //viewbag aanmaken
            var list = new List<string>()
            {
                "08:00 - 09:00",
                "09:00 - 10:00",
                "10:00 - 11:00",
                "11:00 - 12:00",
                "12:00 - 13:00",
                "13:00 - 14:00",
                "14:00 - 15:00",
                "16:00 - 17:00",
                "18:00 - 19:00",
                "19:00 - 20:00",
                "20:00 - 21:00",
                "21:00 - 22:00",
                "22:00 - 23:00"
            };
            ViewBag.list = list;

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(TimeslotViewModel timeslotViewModel)
        {
            TempData["TimeslotCreated"] = "Succesfully created Timeslot: '" + timeslotViewModel.Day + "' at '" + timeslotViewModel.Timeslots + "'";
            Timeslot time = new Timeslot(timeslotViewModel.Day, timeslotViewModel.Timeslots, timeslotViewModel.Maxreservations);
            timeslotContainer.AddOneTimeslot(time);
            return RedirectToAction(nameof(Index));
        }

        // GET: Timeslot/Edit/5
        public IActionResult Edit(int id)
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            //viewbag aanmaken
            var list = new List<string>()
            {
                "08:00 - 09:00",
                "09:00 - 10:00",
                "10:00 - 11:00",
                "11:00 - 12:00",
                "12:00 - 13:00",
                "13:00 - 14:00",
                "14:00 - 15:00",
                "16:00 - 17:00",
                "18:00 - 19:00",
                "19:00 - 20:00",
                "20:00 - 21:00",
                "21:00 - 22:00",
                "22:00 - 23:00"
            };
            ViewBag.list = list;

            TimeslotViewModel timeslotViewModel = new TimeslotViewModel();
            timeslotViewModel = FetchById(id);
            return View(timeslotViewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TimeslotViewModel timeslotViewModel)
        {
            TempData["TimeslotEdited"] = "Succesfully edited Timeslot with new: '" + timeslotViewModel.Day + "' at '" + timeslotViewModel.Timeslots + "'";

            Timeslot time = new Timeslot(timeslotViewModel.TimeslotID, timeslotViewModel.Day, timeslotViewModel.Timeslots, timeslotViewModel.Maxreservations);
            timeslot.EditOneTimeslotById(time);

            return RedirectToAction(nameof(Index));
        }

        // GET: Timeslot/Delete/5
        public IActionResult Delete(int id)
        {
            if (HttpContext.Session.GetInt32("UserID") == null) { Response.Redirect("/Login/Index"); }

            TimeslotViewModel timeslotViewModel = new TimeslotViewModel();
            timeslotViewModel = FetchById(id);

            return View(timeslotViewModel);
        }

        // POST: Timeslot/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id, TimeslotViewModel timeslotViewModel)
        {
            TempData["TimeslotDeleted"] = "Succesfully deleted Timeslot with: '" + timeslotViewModel.Day + "' at '" + timeslotViewModel.Timeslots + "'";

            reservationContainer.DeleteAllReservationsByTimeslotId(id);
            timeslotContainer.DeleteOneTimeslotById(id);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("CreateNewDay")]
        public IActionResult CreateNewWeek()
        {
            foreach (Timeslot timeslot in timeslotContainer.GetTimeslotsByDay(DateTime.Now.ToString("dd-MM-yyyy")))
            {
                timeslotContainer.DeleteOneTimeslotById(timeslot.TimeslotID);
            }

            timeslotContainer.NewDay();

            TempData["NewDayadded"] = "New day added, current day removed";

            return RedirectToAction(nameof(Index));
        }

        [NonAction]
        public TimeslotViewModel FetchById(int id)
        {
            TimeslotViewModel timeslotViewModel = new TimeslotViewModel();

            Timeslot timeslot = timeslotContainer.GetOneTimeslotById(id);

            timeslotViewModel.TimeslotID = timeslot.TimeslotID;
            timeslotViewModel.Day = timeslot.Day;
            timeslotViewModel.Timeslots = timeslot.Timeslots;
            timeslotViewModel.Currentreservations = reservation.CurrentReservations(id);
            timeslotViewModel.Maxreservations = timeslot.Maxreservations;

            return timeslotViewModel;
        }
    }
}

PresentationLayer2/Views/Timeslot/Create.cshtml
@model PresentationLayer2.Models.TimeslotViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create new timeslot</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DropDownListFor(Model => Model.Timeslots, new SelectList(ViewBag.list))
                <label asp-for="Timeslots" class="control-label"></label>
                @*<input asp-for="Timeslots" class="form-control" />*@
                <span asp-validation-for="Timeslots" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Maxreservations" class="control-label"></label>
                <input asp-for="Maxreservations" class="form-control" />
                <span asp-validation-for="Maxreservations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PresentationLayer2/Views/Timeslot/Delete.cshtml
@model PresentationLayer2.Models.TimeslotViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete timeslot</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4></h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Day)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Timeslots)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Timeslots)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Currentreservations)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Currentreservations)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Maxreservations)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Maxreservations)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TimeslotID" />
        <input type="hidden" asp-for="Day" />
        <input type="hidden" asp-for="Timeslots" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PresentationLayer2/Views/Timeslot/Edit.cshtml
@model PresentationLayer2.Models.TimeslotViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4></h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TimeslotID" />
            <div class="form-group">
                <label asp-for="Day" class="control-label"></label>
                <input asp-for="Day" class="form-control" />
                <span asp-validation-for="Day" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DropDownListFor(Model => Model.Timeslots, new SelectList(ViewBag.list))
                <label asp-for="Timeslots" class="control-label"></label>
                @*<input asp-for="Timeslots" class="form-control" />*@
                <span asp-validation-for="Timeslots" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Currentreservations" class="control-label"></label>
                <input asp-for="Currentreservations" class="form-control" />
                <span asp-validation-for="Currentreservations" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Maxreservations" class="control-label"></label>
                <input asp-for="Maxreservations" class="form-control" />
                <span asp-validation-for="Maxreservations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PresentationLayer2/Views/Timeslot/Index.cshtml
@model IEnumerable<TimeslotViewModel>

@{
    ViewData["Title"] = "All available timeslots";
}

<div class="jumbotron-fluid">
    <h1 class="text-center">@ViewData["Title"]</h1>
</div>

<form method="post" autocomplete="off">
    @using (Html.BeginForm("Index", "Timeslot", FormMethod.Get))
    {
        <p>Search for day</p>
        @Html.TextBox("searchPhrase")
        <input type="submit" value="search" />
        <p></p>
    }

    @using (Html.BeginForm("Index", "Timeslot", FormMethod.Post))
    {
        <input type="submit" value="viewAll" />
    }

    <p>

    </p>

    @using (Html.BeginForm("CreateNewDay", "Timeslot", FormMethod.Post))
    {
        <input type="submit" value="NewDay" />
    }
</form>


@if (TempData["TimeslotCreated"] != null)
{
    <div class="alert alert-success">
        <strong> Succes! </strong>  @TempData["TimeslotCreated"]
    </div>
}

@if (TempData["TimeslotEdited"] != null)
{
    <div class="alert alert-success">
        <strong> Succes! </strong>  @TempData["TimeslotEdited"]
    </div>
}

@if (TempData["TimeslotDeleted"] != null)
{
    <div class="alert alert-success">
        <strong> Succes! </strong>  @TempData["TimeslotDeleted"]
    </div>
}

@if (TempData["NewDayadded"] != null)
{
    <div class="alert alert-success">
        <strong> Succes! </strong>  @TempData["NewDayadded"]
    </div>
}

<p>

</p>

<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>
                Day
            </th>
            <th>
                Timeslot
            </th>
            <th>
                Currentreservations
            </th>
            <th>
                Maxreservations
            </th>
            <th>
                <a asp-action="Create">Create New</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(Modelitem => item.Day)
                </td>
                <td>
                    @Html.DisplayFor(Modelitem => item.Timeslots)
                </td>
                <td>
                    @Html.DisplayFor(Modelitem => item.Currentreservations)
                </td>
                <td>
                    @Html.DisplayFor(Modelitem => item.Maxreservations)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.TimeslotID">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.TimeslotID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>